import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Providers } from '@/providers/ThemeProvider';
import  ReduxProvider  from '@/providers/redux-provider';

import { Inter, Instrument_Sans } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const instrument = Instrument_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Providers>
          <ReduxProvider>
            <main className="flex min-h-screen flex-col justify-between max-w-[90rem] mx-auto w-full bg-white dark:bg-dark-200">
              {children}
            </main>
          </ReduxProvider>
        </Providers>
      </body>
    </html>
  );
}
