import { nanoid } from 'nanoid';
import { LuHome } from 'react-icons/lu';
import { IoCalendarOutline } from 'react-icons/io5';
import { RiUserVoiceLine } from 'react-icons/ri';
import { BiSpreadsheet } from 'react-icons/bi';
import { GrNotification } from 'react-icons/gr';
import { PiChatsCircleLight } from 'react-icons/pi';
import { FiSettings } from 'react-icons/fi';
import { TbNotes } from 'react-icons/tb';
import { CgProfile } from "react-icons/cg";

const sidebarData = [
  {
    id: nanoid(),
    title: 'home',
    icon: <LuHome />,
  },
  {
    id: nanoid(),
    title: 'events',
    icon: <IoCalendarOutline />,
  },
  {
    id: nanoid(),
    title: 'speakers',
    icon: <RiUserVoiceLine />,
  },
  {
    id: nanoid(),
    title: 'reports',
    icon: <BiSpreadsheet />,
  },
  {
    id: nanoid(),
    title: 'notifications',
    icon: <GrNotification />,
  },
  {
    id: nanoid(),
    title: 'messages',
    icon: <PiChatsCircleLight />,
  },
  {
    id: nanoid(),
    title: 'settings',
    icon: <FiSettings />,
  },
];
export const downNavBar = [
  {
    id: nanoid(),
    title: 'home',
    icon: <LuHome />,
  },
  {
    id: nanoid(),
    title: 'events',
    icon: <IoCalendarOutline />,
  },
  {
    id: nanoid(),
    title: 'speakers',
    icon: <RiUserVoiceLine />,
  },
  {
    id: nanoid(),
    title: 'reports',
    icon: <TbNotes />,
  },
  {
    id: nanoid(),
    title: 'profile',
    icon: <CgProfile />,
  },
];

export const dashboardCards = [
  {
    id: nanoid(),
    title: 'Total Events',
    amount: '100,000',
    number: 5.0,
  },
  {
    id: nanoid(),
    title: 'Active Speakers',
    amount: '25',
    number: -5.0,
  },
  {
    id: nanoid(),
    title: 'Total Registrations',
    amount: '300',
    number: 5.0,
  },
  {
    id: nanoid(),
    title: 'Total Revenue',
    amount: '$500,000',
    number: 5.0,
  },
];

export const chartData = [
  { name: 'Jan', value: 800 },
  { name: 'Feb', value: 900 },
  { name: 'Mar', value: 600 },
  { name: 'Apr', value: 700 },
  { name: 'May', value: 1000 },
  { name: 'Jun', value: 500 },
  { name: 'Jul', value: 800 },
  { name: 'Aug', value: 700 },
  { name: 'Sep', value: 600 },
  { name: 'Oct', value: 900 },
  { name: 'Nov', value: 1000 },
  { name: 'Dec', value: 700 },
];

export const newsItems = [
  {
    id: 1,
    title: 'Latest News & Updates',
    description:
      'Turpis interdum nunc varius ornare dignissim pretium. Massa ornare quis aliquet sed vitae. Sed velit nisi, fermentum erat.',
    image: '/assets/slide1.jpg',
  },
  {
    id: 2,
    title: 'Upcoming Event',
    description:
      'Etiam fringilla purus, erat fringilla tincidunt quisque non. Pellentesque in ut tellus.',
    image: '/assets/slide2.jpg',
  },
  {
    id: 3,
    title: 'Community Update',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero.',
    image: '/assets/slide4.jpg',
  },
];

export const rowSelect = [10, 12, 14, 16, 20];

export const sortSelect = ['most recent', 'least recent', 'shuffle'];
export const statusSelect = ['in pending', 'completed'];

export const eventData = [
  {
    id: 1,
    eventName: 'Synchronised disintermediate encryption',
    date: '2025-05-19',
    speaker: 'Stephanie Rice',
    status: 'In Progress',
    description: 'Exploring synchronization in encryption techniques.',
  },
  {
    id: 2,
    eventName: 'Devolved leading edge benchmark',
    date: '2025-01-06',
    speaker: 'Eloise Swift',
    status: 'Completed',
    description: 'Latest benchmarks in cutting-edge technology.',
  },
  {
    id: 3,
    eventName: 'Implemented user-facing info-mediaries',
    date: '2025-03-15',
    speaker: 'Pauline Glover',
    status: 'Completed',
    description: 'Discussing implementation of user-centric platforms.',
  },
  {
    id: 4,
    eventName: 'Organic disintermediate time-frame',
    date: '2025-09-03',
    speaker: 'Kelli Kerluke',
    status: 'In Progress',
    description: 'Time management without intermediaries.',
  },
  {
    id: 5,
    eventName: 'Mandatory 4th generation portal',
    date: '2025-06-26',
    speaker: 'Alice Wisozk',
    status: 'In Progress',
    description: 'Advancing portal functionalities to the next level.',
  },
  {
    id: 6,
    eventName: 'Reverse-engineered 24/7 functionalities',
    date: '2025-03-27',
    speaker: 'Milton Goodwin',
    status: 'Completed',
    description: 'Exploring reverse-engineering for constant uptime.',
  },
  {
    id: 7,
    eventName: 'Configurable foreground concept',
    date: '2025-09-03',
    speaker: 'Bernadette K.',
    status: 'Completed',
    description: 'Customizable front-end concepts for modern apps.',
  },
  {
    id: 8,
    eventName: 'Synchronised radical orchestration',
    date: '2025-01-13',
    speaker: 'Charlie Kihn',
    status: 'In Progress',
    description: 'Orchestration strategies for complex systems.',
  },
  {
    id: 9,
    eventName: 'Progressive systematic neural-net',
    date: '2025-02-04',
    speaker: 'Kathryn Schmeler',
    status: 'Completed',
    description: 'Innovations in neural network architecture.',
  },
  {
    id: 10,
    eventName: 'Optimized non-volatile structure',
    date: '2025-02-17',
    speaker: 'Milton Swift',
    status: 'Completed',
    description: 'Optimizing storage for non-volatile environments.',
  },
  {
    id: 11,
    eventName: 'Total tertiary application',
    date: '2025-07-21',
    speaker: 'Mae Weimann',
    status: 'Completed',
    description: 'Comprehensive applications for tertiary markets.',
  },
  {
    id: 12,
    eventName: 'Exclusive maximized superstructure',
    date: '2025-05-05',
    speaker: 'Wallace Hauck',
    status: 'Completed',
    description: 'Maximizing scalability with exclusive structures.',
  },
  {
    id: 13,
    eventName: 'Cross-platform global software',
    date: '2025-08-30',
    speaker: 'Sandy Haag I',
    status: 'Completed',
    description: 'Developing global solutions across platforms.',
  },
  {
    id: 14,
    eventName: 'Innovative didactic open system',
    date: '2025-01-28',
    speaker: 'Jeff Hills',
    status: 'In Progress',
    description: 'Educational open systems for dynamic learning.',
  },
  {
    id: 15,
    eventName: 'Quality-focused 6th generation superstructure',
    date: '2025-06-06',
    speaker: 'Leslie Little',
    status: 'Completed',
    description: 'Enhancing superstructure quality in gen-6 systems.',
  },
  {
    id: 16,
    eventName: 'Public-key fault-tolerant encryption',
    date: '2025-07-23',
    speaker: 'Roman Stolteerg',
    status: 'Completed',
    description: 'Ensuring encryption reliability in public systems.',
  },
  {
    id: 17,
    eventName: 'Team-oriented contextually-based system engine',
    date: '2025-08-15',
    speaker: 'Dana McGlynn',
    status: 'In Progress',
    description: 'Context-based engines for collaborative teams.',
  },
  {
    id: 18,
    eventName: 'Seamless national local area network',
    date: '2025-01-27',
    speaker: 'Mr. Roberto',
    status: 'Completed',
    description: 'Building seamless national network infrastructure.',
  },
  {
    id: 19,
    eventName: 'Switchable leading edge conglomeration',
    date: '2025-07-14',
    speaker: 'Irene Okuneva',
    status: 'In Progress',
    description: 'Switchable systems for leading-edge collaboration.',
  },
  {
    id: 20,
    eventName: 'Self-enabling context-sensitive time-frame',
    date: '2025-05-31',
    speaker: 'Jan Russel',
    status: 'In Progress',
    description: 'Time-sensitive self-enabling processes.',
  },
  {
    id: 21,
    eventName: 'Mandatory zero administration interface',
    date: '2025-05-17',
    speaker: 'Velma Gr.',
    status: 'In Progress',
    description: 'Zero admin systems for simplified management.',
  },
  {
    id: 22,
    eventName: 'Reduced explicit customer loyalty',
    date: '2025-03-15',
    speaker: 'Norman Block',
    status: 'In Progress',
    description: 'Minimizing customer churn through targeted efforts.',
  },
  {
    id: 23,
    eventName: 'Managed even-keeled ability',
    date: '2024-11-10',
    speaker: 'Ro. Schumm',
    status: 'In Progress',
    description: 'Balanced management for steady capabilities.',
  },
  {
    id: 24,
    eventName: 'Devolved incremental collaboration',
    date: '2024-11-24',
    speaker: 'Bertha Abshire',
    status: 'In Progress',
    description: 'Collaborative incremental processes for growth.',
  },
  {
    id: 25,
    eventName: 'Front-line user-facing core',
    date: '2025-09-03',
    speaker: 'Patsy Johns',
    status: 'In Progress',
    description: 'User-centric solutions at the core of innovation.',
  },
  {
    id: 26,
    eventName: 'Inverse multi-tasking strategy',
    date: '2025-07-15',
    speaker: 'Jamie Baumbach',
    status: 'Completed',
    description: 'Strategies for efficient multi-tasking frameworks.',
  },
  {
    id: 27,
    eventName: 'De-engineered 24/7 adapter',
    date: '2025-08-08',
    speaker: 'Minnie Spencer',
    status: 'Completed',
    description: 'Adapting systems for round-the-clock operation.',
  },
  {
    id: 28,
    eventName: 'Fully-configurable scalable array',
    date: '2025-04-13',
    speaker: 'Isaac Legros',
    status: 'Completed',
    description: 'Scalable systems for maximum configuration.',
  },
  {
    id: 29,
    eventName: 'Balanced executive policy',
    date: '2024-11-26',
    speaker: 'Tina Hackett',
    status: 'In Progress',
    description: 'Strategizing balanced executive decision-making.',
  },
  {
    id: 30,
    eventName: 'Multi-lateral solution-oriented conglomeration',
    date: '2025-03-17',
    speaker: 'Ben Farrell',
    status: 'In Progress',
    description: 'Developing multi-lateral collaborative solutions.',
  },
  {
    id: 31,
    eventName: 'Holistic tangible leverage',
    date: '2025-05-04',
    speaker: 'Marsha Baumbach',
    status: 'Completed',
    description: 'Leverage tangible assets for holistic development.',
  },
  {
    id: 32,
    eventName: 'Interchangeable directional extranet',
    date: '2025-02-21',
    speaker: 'Clifton Bartoletti',
    status: 'In Progress',
    description: 'Developing directional extranet for flexible exchange.',
  },
  {
    id: 33,
    eventName: 'Automated responsive migration',
    date: '2025-06-19',
    speaker: 'Adele Wolf',
    status: 'Completed',
    description: 'Migrating systems with automated, responsive tools.',
  },
  {
    id: 34,
    eventName: 'Visionary user-facing knowledge base',
    date: '2025-03-23',
    speaker: 'Bennie Sanford',
    status: 'Completed',
    description: 'Building',
  },
  {
    id: 35,
    eventName: 'Upgradable value-added encryption',
    date: '2025-04-02',
    speaker: 'Luke Nader',
    status: 'Completed',
    description: 'Advancements in upgradable encryption methods.',
  },
  {
    id: 36,
    eventName: 'Streamlined regional neural-net',
    date: '2025-03-20',
    speaker: 'Pat Welch',
    status: 'Completed',
    description: 'Developing efficient regional neural networks.',
  },
  {
    id: 37,
    eventName: 'Secured multi-tier architecture',
    date: '2025-06-22',
    speaker: 'Debbie Harber',
    status: 'In Progress',
    description: 'Securing multi-tiered system architecture.',
  },
  {
    id: 38,
    eventName: 'Operative uniform standardization',
    date: '2025-07-05',
    speaker: 'Trevor Koch',
    status: 'Completed',
    description: 'Creating uniform standards for operational efficiency.',
  },
  {
    id: 39,
    eventName: 'Down-sized integrated matrices',
    date: '2025-08-29',
    speaker: 'Ruth Hyatt',
    status: 'Completed',
    description: 'Optimizing system matrices through integration.',
  },
  {
    id: 40,
    eventName: 'Realigned cross-platform schema',
    date: '2025-09-17',
    speaker: 'Pat Mueller',
    status: 'Completed',
    description: 'Schema improvements across multiple platforms.',
  },
  {
    id: 41,
    eventName: 'Decentralized modular orchestration',
    date: '2025-07-28',
    speaker: 'Luis Stokes',
    status: 'In Progress',
    description: 'Orchestrating decentralized modular systems.',
  },
  {
    id: 42,
    eventName: 'Total heuristic framework',
    date: '2025-03-19',
    speaker: 'Jesse Waters',
    status: 'Completed',
    description: 'Heuristic frameworks for comprehensive systems.',
  },
  {
    id: 43,
    eventName: 'Intuitive synchronized paradigm',
    date: '2025-02-28',
    speaker: 'Cory Kihn',
    status: 'In Progress',
    description: 'Synchronized paradigms for intuitive systems.',
  },
  {
    id: 44,
    eventName: 'Monitored dynamic middleware',
    date: '2025-09-01',
    speaker: 'Marcia Brown',
    status: 'In Progress',
    description: 'Dynamic monitoring for middleware layers.',
  },
  {
    id: 45,
    eventName: 'Centralized next-gen cloud service',
    date: '2025-08-14',
    speaker: 'Geraldine Fisher',
    status: 'Completed',
    description: 'Next-gen cloud services for centralized networks.',
  },
  {
    id: 46,
    eventName: 'Polarized uniform hierarchy',
    date: '2025-07-03',
    speaker: 'Julio Treutel',
    status: 'In Progress',
    description: 'Polarized systems for uniform hierarchical models.',
  },
  {
    id: 47,
    eventName: 'Advanced fault-tolerant grid',
    date: '2025-01-21',
    speaker: 'Alma Macejkovic',
    status: 'Completed',
    description: 'Building fault-tolerant grids for advanced systems.',
  },
  {
    id: 48,
    eventName: 'Versatile interactive protocol',
    date: '2025-08-10',
    speaker: 'Felicia Mertz',
    status: 'Completed',
    description: 'Interactive protocols for versatile communication.',
  },
  {
    id: 49,
    eventName: 'Virtualized holistic infrastructure',
    date: '2025-02-22',
    speaker: 'Everett Jacobi',
    status: 'In Progress',
    description: 'Virtualizing infrastructures for holistic solutions.',
  },
  {
    id: 50,
    eventName: 'Re-contextualized seamless mobility',
    date: '2025-06-27',
    speaker: 'Shannon Yost',
    status: 'In Progress',
    description: 'Enhancing mobility through seamless transitions.',
  },
  {
    id: 51,
    eventName: 'Object-based autonomous algorithm',
    date: '2025-04-18',
    speaker: 'April Olson',
    status: 'Completed',
    description: 'Autonomous algorithms using object-based models.',
  },
  {
    id: 52,
    eventName: 'Self-configurable real-time system',
    date: '2025-07-09',
    speaker: 'Abigail Prosacco',
    status: 'Completed',
    description: 'Real-time systems that adapt via self-configuration.',
  },
  {
    id: 53,
    eventName: 'Interactive strategic orchestration',
    date: '2025-09-21',
    speaker: 'Timothy Lang',
    status: 'Completed',
    description: 'Strategic orchestration of interactive systems.',
  },
  {
    id: 54,
    eventName: 'Customizable cross-media engine',
    date: '2025-06-29',
    speaker: 'Faith Walter',
    status: 'In Progress',
    description: 'Cross-media engines with customizable options.',
  },
  {
    id: 55,
    eventName: 'Balanced user-facing architecture',
    date: '2025-03-12',
    speaker: 'Kaitlyn Kuvalis',
    status: 'Completed',
    description: 'Creating balanced architecture for user-facing systems.',
  },
  {
    id: 56,
    eventName: 'Virtual upward-trending algorithm',
    date: '2025-01-19',
    speaker: 'Justin Ernser',
    status: 'Completed',
    description: 'Algorithms that predict upward trends in virtual data.',
  },
  {
    id: 57,
    eventName: 'Cloned intuitive application',
    date: '2025-02-01',
    speaker: 'Kayla Fadel',
    status: 'In Progress',
    description: 'Developing intuitive clones of modern applications.',
  },
  {
    id: 58,
    eventName: 'Operative global neural-net',
    date: '2025-05-23',
    speaker: 'Rex Hane',
    status: 'Completed',
    description: 'Global neural networks for operational advancements.',
  },
  {
    id: 59,
    eventName: 'Re-engineered modular adapter',
    date: '2025-09-29',
    speaker: 'Blake Stokes',
    status: 'In Progress',
    description: 'Re-engineering modular adapters for flexible systems.',
  },
  {
    id: 60,
    eventName: 'Secured systematic workflow',
    date: '2025-07-26',
    speaker: 'Madison McClure',
    status: 'In Progress',
    description: 'Securing systematic workflows for efficient processes.',
  },
  {
    id: 61,
    eventName: 'Front-end heuristic interface',
    date: '2025-02-20',
    speaker: 'Kimberly Williamson',
    status: 'Completed',
    description: 'Creating heuristic interfaces for front-end users.',
  },
  {
    id: 62,
    eventName: 'Distributed wireless architecture',
    date: '2025-08-03',
    speaker: 'Kristin Trantow',
    status: 'In Progress',
    description: 'Architecting distributed wireless systems.',
  },
  {
    id: 63,
    eventName: 'Phased multi-channel solution',
    date: '2025-05-09',
    speaker: 'Chad Harber',
    status: 'Completed',
    description: 'Phased solutions for multi-channel platforms.',
  },
  {
    id: 64,
    eventName: 'Multi-layered cross-functional matrix',
    date: '2025-09-30',
    speaker: 'Annie Erdman',
    status: 'In Progress',
    description: 'Cross-functional systems with multi-layered matrices.',
  },
  {
    id: 65,
    eventName: 'Synergistic next-gen framework',
    date: '2025-06-02',
    speaker: 'Wes Mertz',
    status: 'Completed',
    description: 'Next-gen frameworks powered by synergy.',
  },
  {
    id: 66,
    eventName: 'Automated scalable engine',
    date: '2025-01-18',
    speaker: 'Chester Corkery',
    status: 'Completed',
    description: 'Engines designed for automation and scalability.',
  },
  {
    id: 67,
    eventName: 'Synchronised proactive architecture',
    date: '2025-04-14',
    speaker: 'Eleanor O\'Keefe',
    status: 'In Progress',
    description: 'Proactive architecture with synchronized elements.',
  },
  {
    id: 68,
    eventName: 'Reduced forward-thinking system',
    date: '2025-06-24',
    speaker: 'Virginia Quitzon',
    status: 'Completed',
    description: 'Forward-thinking systems designed for efficiency.',
  },
  {
    id: 69,
    eventName: 'Centralized next-gen platform',
    date: '2025-03-01',
    speaker: 'Cecil Heller', status: 'In Progress', description: 'Next-gen platforms for centralized operations.', }, 
    { id: 70, eventName: 'Dynamic integrated backend', date: '2025-05-19', speaker: 'Rosalinda Krajcik', status: 'Completed', description: 'Integrated backend solutions for dynamic systems.', }, 
    { id: 71, eventName: 'Integrated multi-disciplinary strategy', date: '2025-08-12', speaker: 'Rodrigo Roob', status: 'In Progress', description: 'Strategies integrating multiple disciplines.', }, { id: 72, eventName: 'Virtualized systematic management', date: '2025-09-11', speaker: 'Diana Rippin', status: 'Completed', description: 'Managing systems through virtualization.', }, { id: 73, eventName: 'Refined user-centric model', date: '2025-02-15', speaker: 'Lorenzo Corwin', status: 'In Progress', description: 'Models focused on user-centric designs.', }, { id: 74, eventName: 'Extended cross-platform integration', date: '2025-04-29', speaker: 'Rosie Lesch', status: 'Completed', description: 'Integration strategies for cross-platform solutions.', }, { id: 75, eventName: 'Holistic mobile framework', date: '2025-01-10', speaker: 'Arnold Boehm', status: 'In Progress', description: 'Frameworks for holistic mobile development.', }, { id: 76, eventName: 'Global multi-node strategy', date: '2025-06-05', speaker: 'Dena Ritchie', status: 'Completed', description: 'Multi-node strategies for global systems.', }, { id: 77, eventName: 'Integrated open-source platform', date: '2025-07-22', speaker: 'Tracy Bradtke', status: 'In Progress', description: 'Developing open-source platforms with integrated solutions.', }, { id: 78, eventName: 'Synchronized robust infrastructure', date: '2025-09-09', speaker: 'Adan Tremblay', status: 'Completed', description: 'Building robust infrastructures through synchronization.', }, { id: 79, eventName: 'Modular scalable architecture', date: '2025-02-17', speaker: 'Wilma Hickle', status: 'In Progress', description: 'Architectural solutions designed for scalability.', }, { id: 80, eventName: 'Dynamic multi-layered network', date: '2025-05-06', speaker: 'Emilio Walker', status: 'Completed', description: 'Dynamic networks with multi-layered designs.', }, { id: 81, eventName: 'Cross-functional comprehensive solution', date: '2025-08-23', speaker: 'Jerry Wiegand', status: 'In Progress', description: 'Comprehensive solutions that cross functional boundaries.', }, { id: 82, eventName: 'Standardized holistic structure', date: '2025-01-16', speaker: 'Reggie Larkin', status: 'Completed', description: 'Holistic structures with standardized processes.', }, { id: 83, eventName: 'Next-gen adaptive system', date: '2025-09-02', speaker: 'Ernesto Koelpin', status: 'In Progress', description: 'Adaptive systems for next-gen applications.', }, { id: 84, eventName: 'Innovative analytical framework', date: '2025-03-30', speaker: 'Cleo Lemke', status: 'Completed', description: 'Frameworks for innovative analytical solutions.', }, { id: 85, eventName: 'User-centric modular design', date: '2025-04-25', speaker: 'Herbert Gutmann', status: 'In Progress', description: 'Modular designs focused on user needs.', }, { id: 86, eventName: 'Automated secure connection', date: '2025-08-08', speaker: 'Devon Wiegand', status: 'Completed', description: 'Establishing automated secure connections.', }, { id: 87, eventName: 'Integrated data-driven model', date: '2025-02-12', speaker: 'Janice Kreiger', status: 'In Progress', description: 'Data-driven models for integrated systems.', }, { id: 88, eventName: 'Comprehensive proactive framework', date: '2025-09-15', speaker: 'Verna Krajcik', status: 'Completed', description: 'Proactive frameworks for comprehensive applications.', }, { id: 89, eventName: 'Holistic interactive strategy', date: '2025-06-10', speaker: 'Tessa Schuster', status: 'In Progress', description: 'Interactive strategies for holistic solutions.', }, { id: 90, eventName: 'Synergistic adaptive architecture', date: '2025-07-14', speaker: 'Adele Powlowski', status: 'Completed', description: 'Adaptive architecture that harnesses synergy.', }, { id: 91, eventName: 'Intelligent multi-channel system', date: '2025-03-11', speaker: 'Maximillian Becker', status: 'In Progress', description: 'Multi-channel systems with intelligent designs.', }, { id: 92, eventName: 'Modular user-centric interface', date: '2025-08-30', speaker: 'Chloe Krajcik', status: 'Completed', description: 'User-centric interfaces with modular designs.', }, { id: 93, eventName: 'Interconnected strategic architecture', date: '2025-01-23', speaker: 'Laurel Collins', status: 'In Progress', description: 'Strategic architecture that emphasizes interconnectivity.', }, { id: 94, eventName: 'Flexible dynamic platform', date: '2025-09-06', speaker: 'Virgil Daniel', status: 'Completed', description: 'Platforms designed for flexibility and dynamism.', }, { id: 95, eventName: 'Global real-time solution', date: '2025-05-11', speaker: 'Sofia O', status: 'In Progress', description: 'Real-time solutions for global applications.', }, 
      { id: 96, eventName: 'Scalable next-gen system', date: '2025-02-26', speaker: 'Zelda Wyman', status: 'Completed', description: 'Next-gen systems designed for scalability.', }, { id: 97, eventName: 'Enhanced user-facing solution', date: '2025-03-04', speaker: 'Aidan Kuhlman', status: 'In Progress', description: 'User-facing solutions with enhanced features.', }, { id: 98, eventName: 'Interoperable adaptive model', date: '2025-08-18', speaker: 'Carson O', status: 'Completed', description: 'Adaptive models that support interoperability.', }, { id: 99, eventName: 'Custom cloud-based architecture', date: '2025-07-13', speaker: 'Katherine Schneider', status: 'In Progress', description: 'Cloud-based architecture customized for specific needs.', }, { id: 100, eventName: 'Intelligent cross-platform integration', date: '2025-09-25', speaker: 'Evelyn Champlin', status: 'Completed', description: 'Intelligent integration across multiple platforms.', },
]

export default sidebarData;
